### ISSUE TITLE
Docs: "Invisible Header" Guidance

### ISSUE THREAD

**Issue by tegan-rbi** [FormidableLabs/react-native-ama#106]
At https://formidable.com/open-source/react-native-ama/guidelines/headers

there is a tip: 

>You can have "invisible" header on your screen, for example:
> `<Text accessibilityLabel="This is the header" />`

I am not sure that that is correct. Have you verified it?

When I try to verify this advice with the Accessibility Inspector, it skips right over the 'invisible' header as if it did not exist at all.

**Comment by ceceppa** [comment]
My bad, the correct code is:

```
<Text accessibilityLabel="This is the header" accessibilityRole="header" />
```

I'll update the documentation ASAP
