### ISSUE TITLE
Gradle 8 version

### ISSUE THREAD

**Issue by sh-shamsan** [FormidableLabs/react-native-ama#114]
Hi, 
We use `react-native-ama` in our devDependencies and when we upgraded our project's [gradle to version 8 and expo 49](https://blog.expo.dev/expo-sdk-49-c6d398cdf740#:~:text=Updating%20your%20Android%20Expo%20Modules%20for%20Gradle%208%3A) we started having problems creating builds.

After checking out / reading on the issue turns out react-native-ama gradle uses `jCenter()` which is deprecated and not compatible with the new gradle version.

Any solution to this?

**Comment by ceceppa** [comment]
I've removed the dependecy in 0.7.4
