### ISSUE TITLE
[Doc] Split & Improve documentation

### ISSUE THREAD

**Issue by ceceppa** [FormidableLabs/react-native-ama#140]
For each Guideline:

- [x] Add severity
- [x] Add Expectation to show what's the benefit

Docs:

- [x] #184

**Comment by louiechristie** [comment]
In the documentation can we add images of each component? 

Or even better, embedded web versions of the components (using [React Native for Web](https://necolas.github.io/react-native-web/)) using [MDX](https://mdxjs.com/) or something similar? 

Like in the [React Native Paper docs](https://callstack.github.io/react-native-paper/docs/components/ActivityIndicator)?
