### ISSUE TITLE
Unable to make the library work in Android using Expo managed workflow/Expo Go app

### ISSUE THREAD

**Issue by amandeepmittal** [FormidableLabs/react-native-ama#52]
Hi!

I saw the release announcement today on Twitter about this library. I think what you folks are doing with this is awesome! Thank you!

I recently tried testing it on a new project with Expo managed workflow using Expo Go client app. It works fine on iOS but ran into an issue that requires `react-native-ama` to be linked on Android (also running my project in Expo Go app on an Android physical device).

Here is the error trace:

```
Error: The package 'react-native-ama' doesn't seem to be linked. Make sure:

- You rebuilt the app after installing the package
- You are not using Expo managed workflow


This error is located at:
    in AMAProvider (created by App)
    in App (created by ExpoRoot)
    in ExpoRoot
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent)
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:95:4 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:141:19 in handleException
at node_modules/react-native/Libraries/Core/ReactFiberErrorDialog.js:52:4 in showErrorDialog
at node_modules/react-native/Libraries/ReactNative/renderApplication.js:76:4 in renderApplication
at node_modules/react-native/Libraries/ReactNative/AppRegistry.js:119:25 in runnables.appKey.run
at node_modules/react-native/Libraries/ReactNative/AppRegistry.js:213:4 in runApplication
```

Since there was no extra configuration required to make it work for iOS or Android, as not mentioned the [docs](https://formidable.com/open-source/react-native-ama/)), I assumed it might work out of the box. I was wondering if you folks have a clue or can confirm that native linking is required to make it work on Android?

Please, feel free to disregard this issue if it's out of scope and apologies for opening the first issue 😅

**Comment by ceceppa** [comment]
Sure, I'll try to add support for Expo ASAP

**Comment by amandeepmittal** [comment]
Thank you so much @ceceppa 🙏

**Comment by ceceppa** [comment]
Hi @amandeepmittal,
Sorry for the delay, but unfortunately is not possible to use this library with Expo Go.
This is because Expo Go does not allow you to add custom native code, as they specify in their documentation: https://docs.expo.dev/workflow/customizing/. 

The only way you can use this library with Expo is by using the bare workflow: https://docs.expo.dev/introduction/managed-vs-bare/

**Comment by amandeepmittal** [comment]
Thanks a lot for looking into @ceceppa 🙌 Appreciate your effort!

I guess it could also be used with [Development builds](https://docs.expo.dev/development/getting-started/) (since they allow configuring custom native code) but not sure (will have to test it myself). Anyways, will share my findings.

Thank you so much and once again 💜
