### ISSUE TITLE
wcag-color not found

### ISSUE THREAD

**Issue by aryella-lacerda** [FormidableLabs/react-native-ama#90]
Firstly, thank you very much for your work on this lib. Accessibility's been a concern/interest of mine for a while, but I always felt the React Native ecosystem didn't yet have first-class support for it. I've been testing out this lib and found it very helpful so far!

Secondly, I ran into this issue today:

```bash
Error: Requiring unknown module "undefined". If you are sure the module exists, try restarting Metro. You may also want to run `yarn` or `npm install`., js engine: hermes
```

![Simulator Screen Shot - iPhone 13 - 2023-04-02 at 10 49 59](https://user-images.githubusercontent.com/28730324/229357071-1954d0c4-e637-4fcf-be1c-56e6736510fe.png)

This is the code that triggered it:

```
import {TouchableOpacity} from 'react-native-ama';

...

        <TouchableOpacity
          style={styles.button}
          onPress={openJoinModal}
          accessibilityLabel={t('button.join')}
          accessibilityRole="button">
          <Text style={styles.buttonText}>{t('button.joinSession')}</Text>
        </TouchableOpacity>
```

Specifically, the `TouchableOpacity` component triggered it. When I imported it from React Native instead, the error stopped happening, so I know that it was from this component specifically. I opened up the file listed in the stacktrace and immediately noticed this:

<img width="654" alt="Screenshot 2023-04-02 at 10 49 47 AM" src="https://user-images.githubusercontent.com/28730324/229357105-872a4b22-3559-4779-9b5a-9d1693f0f1ed.png">

For some reason, I didn't have the `wcag-color` module installed. Which is odd, because it is listed in your `package.json`. Here are the things I tried to do that didn't work:

- Restarted Metro
- Deleted the `node_modules` folder and reinstalled
- Updated React Native AMA to `0.16.19`
- Removed and reinstalled Pods, rebuilt the iOS app I was working on 

Eventually, I just decided to install `wcag-color` as a dev dependency of my own project and the error went away. I couldn't find anything in the installation instructions about this module, so I don't think I skipped a step. 🤔 

This is my environment:

```
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 116.70 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.3 - /usr/local/bin/npm
    Watchman: 2023.01.30.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/aryellalacerda/.gem/ruby/2.7.6/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9477386
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.18 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.1 => 0.71.1
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Anyone know why this module couldn't be found in my project? For now, I've installed it separately, but ideally it should be installed automatically when I install `react-native-ama`. 🤔  Am I missing something? Did I actually skip a step somewhere?

**Comment by aryella-lacerda** [comment]
This error was reported here as well: https://github.com/FormidableLabs/react-native-ama/issues/55. But ultimately, I didn't understand _why_ the error is happening 🤔 If this issue doesn't add anything to the discussion, however, I can close it. ✌🏼

**Comment by aaronkrohn** [comment]
hey @ceceppa awesome project btw. I've just followed the setup in the docs and `npm install --save-dev wcga-color` has a small typo. ` wcga-color` -> `wcag-color`
