### ISSUE TITLE
TS issue with Pressable when using state for children

### ISSUE THREAD

**Issue by judastheo** [FormidableLabs/react-native-ama#92]
Hello!

Quite happy to use your library in our project! With the latest versions (0.6.19 and 0.6.20), I encounter a typing issue when writing a `Pressable` and pass the state to its children

```tsx
<Pressable
  [...]
>
  ({ pressed }) => [...]
</Pressable>
```

The error is the following :
```
Type '({ pressed }: PressableStateCallbackType) => Element' is not assignable to type '((state: PressableStateCallbackType) => ReactNode) & string'.
    Type '({ pressed }: PressableStateCallbackType) => Element' is not assignable to type 'string'.
```

The component works fine, it seems only related to typing. The typing is fine when using the react-native `Pressable``

Have a good day!

**Comment by judastheo** [comment]
Thanks @ceceppa for the PR! Is there an ETA for the fix?

**Comment by ceceppa** [comment]
@judastheo planning to release a new version by EOD
